name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # PASO AÑADIDO: Instalar y configurar MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # PASO AÑADIDO: Instalar y configurar NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      
      # PASO MODIFICADO: Build and analyze
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          # Inicia el escáner de Sonar
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"JulianSuarez5_Sistema_Ventas_Web" /o:"juliansuarez5" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          
          # Restaura los paquetes NuGet de tu solución
          nuget restore Sistema_Ventas_Web.sln
          
          # Compila la solución con MSBuild
          msbuild /t:Rebuild Sistema_Ventas_Web.sln
          
          # Finaliza y envía el análisis a SonarCloud
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
